/*
  Warnings:

  - You are about to alter the column `id` on the `Card` table. The data in that column will be cast from `String` to `Int`. This cast may fail. Please make sure the data in the column can be cast.

*/
-- AlterTable
ALTER TABLE "UserBookmarkOnLearningSet" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "UserLikeOnLearningSet" ADD COLUMN     "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- RedefineTables
CREATE TABLE "_prisma_new_Card" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "term" STRING NOT NULL,
    "definition" STRING NOT NULL,
    "learningSetId" STRING NOT NULL,

    CONSTRAINT "Card_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Card" ("definition","id","learningSetId","term") SELECT "definition","id","learningSetId","term" FROM "Card";
DROP TABLE "Card" CASCADE;
ALTER TABLE "_prisma_new_Card" RENAME TO "Card";
ALTER TABLE "Card" ADD CONSTRAINT "Card_learningSetId_fkey" FOREIGN KEY ("learningSetId") REFERENCES "LearningSet"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
