-- CreateEnum
CREATE TYPE "Visibility" AS ENUM ('PUBLIC', 'UNLISTED', 'UNPUBLISHED');

-- CreateTable
CREATE TABLE "auth_user" (
    "id" STRING NOT NULL,
    "email" STRING NOT NULL,
    "username" STRING NOT NULL,
    "displayName" STRING NOT NULL,
    "avatar" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "auth_user_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_key" (
    "id" STRING NOT NULL,
    "hashed_password" STRING,
    "user_id" STRING NOT NULL,
    "primary_key" BOOL NOT NULL,
    "expires" INT8,

    CONSTRAINT "auth_key_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "auth_session" (
    "id" STRING NOT NULL,
    "user_id" STRING NOT NULL,
    "active_expires" INT8 NOT NULL,
    "idle_expires" INT8 NOT NULL,

    CONSTRAINT "auth_session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "LearningSet" (
    "id" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,
    "publishedAt" TIMESTAMP(3),
    "name" STRING NOT NULL,
    "description" STRING NOT NULL,
    "visibility" "Visibility" NOT NULL,
    "tags" STRING[],
    "authorId" STRING NOT NULL,

    CONSTRAINT "LearningSet_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Card" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "term" STRING NOT NULL,
    "definition" STRING NOT NULL,
    "learningSetId" STRING NOT NULL,

    CONSTRAINT "Card_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "UserLikeOnLearningSet" (
    "userId" STRING NOT NULL,
    "learningSetId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserLikeOnLearningSet_pkey" PRIMARY KEY ("userId","learningSetId")
);

-- CreateTable
CREATE TABLE "UserBookmarkOnLearningSet" (
    "userId" STRING NOT NULL,
    "learningSetId" STRING NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "UserBookmarkOnLearningSet_pkey" PRIMARY KEY ("userId","learningSetId")
);

-- CreateTable
CREATE TABLE "UserReportOnLearningSet" (
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "inapropriate" BOOL NOT NULL,
    "privacy" BOOL NOT NULL,
    "spam" BOOL NOT NULL,
    "misleading" BOOL NOT NULL,
    "copyright" BOOL NOT NULL,
    "customReason" STRING,
    "learningSetId" STRING NOT NULL,
    "reporterId" STRING NOT NULL,

    CONSTRAINT "UserReportOnLearningSet_pkey" PRIMARY KEY ("learningSetId","reporterId")
);

-- CreateIndex
CREATE UNIQUE INDEX "auth_user_id_key" ON "auth_user"("id");

-- CreateIndex
CREATE UNIQUE INDEX "auth_user_email_key" ON "auth_user"("email");

-- CreateIndex
CREATE UNIQUE INDEX "auth_user_username_key" ON "auth_user"("username");

-- CreateIndex
CREATE UNIQUE INDEX "auth_key_id_key" ON "auth_key"("id");

-- CreateIndex
CREATE INDEX "auth_key_user_id_idx" ON "auth_key"("user_id");

-- CreateIndex
CREATE UNIQUE INDEX "auth_session_id_key" ON "auth_session"("id");

-- CreateIndex
CREATE INDEX "auth_session_user_id_idx" ON "auth_session"("user_id");

-- AddForeignKey
ALTER TABLE "auth_key" ADD CONSTRAINT "auth_key_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "auth_session" ADD CONSTRAINT "auth_session_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "LearningSet" ADD CONSTRAINT "LearningSet_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Card" ADD CONSTRAINT "Card_learningSetId_fkey" FOREIGN KEY ("learningSetId") REFERENCES "LearningSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserLikeOnLearningSet" ADD CONSTRAINT "UserLikeOnLearningSet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserLikeOnLearningSet" ADD CONSTRAINT "UserLikeOnLearningSet_learningSetId_fkey" FOREIGN KEY ("learningSetId") REFERENCES "LearningSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserBookmarkOnLearningSet" ADD CONSTRAINT "UserBookmarkOnLearningSet_userId_fkey" FOREIGN KEY ("userId") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserBookmarkOnLearningSet" ADD CONSTRAINT "UserBookmarkOnLearningSet_learningSetId_fkey" FOREIGN KEY ("learningSetId") REFERENCES "LearningSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserReportOnLearningSet" ADD CONSTRAINT "UserReportOnLearningSet_learningSetId_fkey" FOREIGN KEY ("learningSetId") REFERENCES "LearningSet"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "UserReportOnLearningSet" ADD CONSTRAINT "UserReportOnLearningSet_reporterId_fkey" FOREIGN KEY ("reporterId") REFERENCES "auth_user"("id") ON DELETE CASCADE ON UPDATE CASCADE;
